[package]
name = "rubik-calculator"
version = "0.1.0"
description = "跨平台网格链式计算器 Rubik Calculator"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
tauri = { version = "2.0.6", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
